name: test
channels:
  - conda-forge
dependencies:
  - obspy
  - pytest-cov
  - fortran-compiler
  # see obspy issue #2912, can be removed after obspy release 1.3.0
  - 'numpy<1.22'
  - 'setuptools=60'

